config/routes.rb
require 'sidekiq/web'

Facepuncher::Application.routes.draw do

  root to: 'projects#show'

  resources :projects do
    member do
      match '/index' => 'projects#show'
    end
  end

  namespace :api do
    resources :project do
      resources :signups
      resources :events
      resources :videos
      resources :images
      resources :feeds
      resources :posts
      resources :facebook_albums
      resources :facebook_events

      resources :polls do
        put 'vote', on: :member
      end

      resources :submissions do
        post 'submit', on: :member
      end
    end
  end

  match '/admin' => 'admin/projects#index', as: 'user_root'

  # ADMIN ROUTES
  devise_for :users

  namespace :admin do
    root to: "projects#index"

    resources :users

    resources :projects do
      post 'queue_deploy', on: :collection

      member do
        get 'activate'
        get 'deactivate'
      end

      resources :signups
      resources :feeds
      resources :facebook_albums
      resources :facebook_events
      resources :view_templates

      resources :videos do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :releases do
        member do
          get 'go_live'
        end
      end

      resources :images do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :events do
        collection do
          post 'import'
        end
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :polls do
        resources :choices

        member do
          get 'activate'
          get 'deactivate'
        end
      end

      resources :submissions do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :posts do
        member do
          put 'up'
          put 'down'
          get 'approve'
          get 'deny'
        end
      end
    end

    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActsAsList::Mongoid

  field :state, type: String, default: 'pending'
  field :name, type: String
  field :type, type: String
  field :start_date, type: DateTime
  field :end_date, type: DateTime
  field :url, type: String
  field :details, type: String

  attr_accessible :name, :type, :start_date, :end_date, :url, :details, :location_attributes

  embeds_one :location, as: :locationable

  accepts_nested_attributes_for :location

  belongs_to :project

  paginates_per 20

  validates :name, :start_date, presence: true

  scope :pending, where(state: "pending")
  scope :approved, where(state: "approved")
  scope :denied, where(state: "denied")
  scope :future, where(:start_date.gt => Time.current)

  state_machine initial: :pending do
    event :approve do
      transition [:pending, :denied] => :approved
    end

    event :deny do
      transition [:pending, :approved] => :denied
    end
  end

  def as_json(options={})
    results = super({ method: location }.merge(options))
    results['start_date'] = start_date.strftime("%a %b %d, %Y %I:%M %p")
    results['end_date'] = end_date.strftime("%a %b %d, %Y %I:%M %p") if end_date
    results
  end
end

app/controllers/admin/events_controller.rb
require 'csv'

class Admin::EventsController < AdminController
  respond_to :html, :json

  def index
    @events = @project.events.page(params[:page])
    respond_with @events
  end

  def new
    @event = @project.events.new
    @event.build_location
    @start_lat, @start_lng = 40.742264, -73.99134079999999
  end

  def edit
    @event = @project.events.find(params[:id])
    @start_lat, @start_lng = @event.location.latitude, @event.location.longitude
  end

  def show
    @event = @project.events.find(params[:id])
    respond_with @event
  end

  def create
    @event = @project.events.new(params[:event])
    @event.move_to_top if @event.save
    respond_with @event, location: [:admin, @project, @event]
  end

  def update
    @event = @project.events.find(params[:id])
    @event.update_attributes(params[:event])
    respond_with @event, location: [:admin, @project, @event]
  end

  def destroy
    @event = @project.events.find(params[:id])
    @event.destroy
    respond_with @event, location: admin_project_events_url do |format|
      format.json { render json: '{ "status":"success" }', status: :ok }
    end
  end

  def approve
    @event = @project.events.find(params[:id])
    @event.approve

    respond_with @event do |format|
      format.html { redirect_to [:admin, @project, @event] }
      format.json { render json: '{ "status":"success" }', status: :ok }
    end
  end

  def deny
    @event = @project.events.find(params[:id])
    @event.deny
    
    respond_with @event do |format|
      format.html { redirect_to [:admin, @project, @event] }
      format.json { render json: '{ "status":"success" }',  status: :ok }
    end
  end

  def import
    logger.debug params[:file].open
    CSV.parse(params[:file].open, {headers: true}) do |row|
      @project.events.create!(name: row['name'], type: row['type'], start_date: Date.strptime(row['start_date'], '%m/%d/%Y'), end_date: Date.strptime(row['end_date'], '%m/%d/%Y'), url: row['url'], details: row['details'], location: Location.new(name: row['location.name'], address: row['location.address'], latitude: row['location.latitude'] || 0, longitude: row['location.longitude'] || 0))
    end
    redirect_to(admin_project_events_url(@project))
  end
end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  before_filter :load_project, :check_for_project

  respond_to :json, :xml

  def index
    params[:sort_direction] ||= "asc"
    
    @events = @project.events
    @events = @events.where(state: params[:state]) if params[:state]
    @events = @events.any_in(type: params[:type].split(",")) if params[:type]
    @events = @events.order_by(params[:sort_column], params[:sort_direction]) if params[:sort_column]
    @events = @events.page(params[:page])
    @events = @events.per(params[:per_page]) if params[:per_page]
    
    respond_with :api, @project, @events
  end

  def show
    @event = @project.events.find(params[:id])

    respond_with :api, @project, @event
  end
end

app/views/admin/events/_form.html.haml
= form_for [:admin, @project, @event], html: {class: "form-horizontal"} do |f|
  - if @event.errors.any?
    .alert.alert-error
      %p
        %b
          = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend= controller_action
    .control-group
      = f.label :name, class: "control-label"
      .controls= f.text_field :name

    .control-group
      = f.label :type, class: "control-label"
      .controls= f.text_field :type

    .control-group
      = f.label :start_date, class: "control-label"
      .controls= f.text_field :start_date, class: "datetimepicker"

    .control-group
      = f.label :end_date, class: "control-label"
      .controls= f.text_field :end_date, class: "datetimepicker"

    .control-group
      = f.label :url, class: "control-label"
      .controls= f.text_field :url

    .control-group
      = f.label :details, class: "control-label"
      .controls= f.text_field :details

    = f.fields_for :location do |l|
      = render partial: 'shared/form_location', locals: {f: l}

    .form-actions
      = link_to "Save", "#", title: "Save", id: "submit-event", class: 'btn btn-primary'

app/views/admin/events/edit.html.haml
%p
	= link_to 'Back', admin_project_events_path(@project), title: "Back", class: "btn btn-inverse"

.row
	.span6
		= render 'form'
	.span6
		.google-map{style: "margin-top: 40px"}
			#map_canvas
			#pano

app/views/admin/events/index.html.haml
%p
  = link_to '<i class="icon-plus"></i> New Event'.html_safe, new_admin_project_event_path(@project), class: "btn", title: "New"
  = link_to '<i class="icon-upload"></i> Import from CSV'.html_safe, "#", class: "btn import", title: "Import from CSV"

.row
  .span3
    = form_tag import_admin_project_events_path(@project.name), multipart: true, class: "well form-inline import-csv" do
      %h6 Import from CSV
      = file_field_tag :file
      %br
      = submit_tag "Upload", disable_with: 'Uploading...', class: "btn"

.well
  %h6 Stats
  #{@project.events.all.count} total

%textarea{class: "tmpl", "data-project" => "#{@project.name}", "data-model" => "#{controller_name}", "data-action" => "#{action_name}"}
  %tr{class: "${state}"}
    %td
      = link_to '${name}', admin_url + '${id}'
      %div{class: "actions ${state}"}
        = link_to '<i class="icon-ok-circle"></i>'.html_safe, admin_url + '${id}/approve.json', remote: true, class: "state approve btn", title: "Approve"
        = link_to '<i class="icon-ban-circle"></i>'.html_safe, admin_url + '${id}/deny.json', remote: true, class: "state deny btn", title: "Deny"
        = link_to '<i class="icon-edit"></i>'.html_safe, admin_url + '${id}/edit', class: "btn", title: "Edit"
        = link_to '<i class="icon-trash"></i>'.html_safe, admin_url + '${id}.json', remote: true, confirm: 'Are you sure?', method: :delete, class: "btn delete", title: "Delete"
    %td ${state}
    %td ${type}
    %td ${start_date}
    %td ${end_date}
    %td ${location.address}
    %td ${location.latitude}
    %td ${location.longitude}

%table.table.table-striped.table-bordered
  %tr
    %th Name
    %th State
    %th Type
    %th Start Date
    %th End Date
    %th Address
    %th Latitude
    %th Longitude

    / %td
    /   = form_for event, url: admin_project_event_path(@project.name, event, format: :json), remote: true, html: { class: 'location_update_form' } do |f|
    /     = f.hidden_field :id
    /     = f.fields_for :location do |l|
    /       = l.hidden_field :address
    /       = l.hidden_field :latitude
    /       = l.hidden_field :longitude
    /     = link_to 'Locate', 'javascript: void(0);', 'data-form-id' => "edit_#{dom_id(event)}", class: "locate btn"

app/views/admin/events/new.html.haml
%p
	= link_to 'Back', admin_project_events_path(@project), title: "Back", class: "btn btn-inverse"

.row
	.span6
		= render 'form'
	.span6
		.google-map{style: "margin-top: 40px"}
			#map_canvas
			#pano

app/views/admin/events/show.html.haml
- content_for :scripts do
  = javascript_include_tag 'https://maps-api-ssl.google.com/maps/api/js?sensor=false'
  :javascript
    $(document).ready(function() {
      var geocoder = new google.maps.Geocoder();

      // map
      var latlng = new google.maps.LatLng(#{@event.location.latitude},#{@event.location.longitude});
      var myOptions = {
        zoom: 15,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

      // street view
      var panoramaOptions = {
        position: latlng,
        pov: {
          heading: 34,
          pitch: 10,
          zoom: 1
        }
      };
      var panorama = new google.maps.StreetViewPanorama(document.getElementById("pano"), panoramaOptions);
      var sv = new google.maps.StreetViewService();

      function processSVData(data, status) {
        if (status == google.maps.StreetViewStatus.OK) {
          panorama.setPano(data.location.pano);
          panorama.setVisible(true);
        }
      }

      sv.getPanoramaByLocation(latlng, 300, processSVData)
    });

- unless notice.blank?
  #notice.alert= notice

%p
  = link_to 'Back', admin_project_events_path(@project), title: "Back", class: "btn btn-inverse"
  = link_to '<i class="icon-plus"></i>'.html_safe, new_admin_project_event_path(@project), title: "New", class: "btn"

%textarea{class: "tmpl", "data-project" => "#{@project.name}", "data-model" => "#{controller_name}", "data-action" => "#{action_name}"}
  %tr{class: "${state}"}
    %td{colspan: 2}
      = link_to '<i class="icon-ok-circle"></i>'.html_safe, admin_url + '${id}/approve.json', remote: true, class: "state approve btn", title: "Approve"
      = link_to '<i class="icon-ban-circle"></i>'.html_safe, admin_url + '${id}/deny.json', remote: true, class: "state deny btn", title: "Deny"
      = link_to '<i class="icon-edit"></i>'.html_safe, admin_url + '${id}/edit', class: "btn", title: "Edit"
      = link_to '<i class="icon-trash"></i>'.html_safe, admin_url + '${id}', confirm: 'Are you sure?', method: :delete, class: "btn delete", title: "Delete"
  
  %tr
    %td Created at
    %td ${created_at}
  %tr
    %td Updated at
    %td ${updated_at}
  %tr
    %td State
    %td ${state}
  %tr
    %td Name
    %td ${name}
  %tr
    %td Type
    %td ${type}
  %tr
    %td URL
    %td ${url}
  %tr
    %td Start Date
    %td ${start_date}
  %tr
    %td End Date
    %td ${end_date}
  %tr
    %td Details
    %td ${details}
  %tr
    %td Location Name
    %td ${location.name}
  %tr
    %td Location Address
    %td ${location.address}
  %tr
    %td Location Latitude
    %td ${location.latitude}
  %tr
    %td Location Longitude
    %td ${location.longitude}

.row
  .span6
    %table.table.table-striped.table-bordered

  .span6
    .google-map
      #map_canvas
      #pano
      %p
        * Showing nearest Street View (within 300 Meters)