config/routes.rb
require 'sidekiq/web'

Facepuncher::Application.routes.draw do

  root to: 'projects#show'

  resources :projects do
    member do
      match '/index' => 'projects#show'
    end
  end

  namespace :api do
    resources :project do
      resources :signups
      resources :events
      resources :videos
      resources :images
      resources :feeds
      resources :posts
      resources :facebook_albums
      resources :facebook_events

      resources :polls do
        put 'vote', on: :member
      end

      resources :submissions do
        post 'submit', on: :member
      end
    end
  end

  match '/admin' => 'admin/projects#index', as: 'user_root'

  # ADMIN ROUTES
  devise_for :users

  namespace :admin do
    root to: "projects#index"

    resources :users

    resources :projects do
      post 'queue_deploy', on: :collection

      member do
        get 'activate'
        get 'deactivate'
      end

      resources :signups
      resources :feeds
      resources :facebook_albums
      resources :facebook_events
      resources :view_templates

      resources :videos do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :releases do
        member do
          get 'go_live'
        end
      end

      resources :images do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :events do
        collection do
          post 'import'
        end
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :polls do
        resources :choices

        member do
          get 'activate'
          get 'deactivate'
        end
      end

      resources :submissions do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :posts do
        member do
          put 'up'
          put 'down'
          get 'approve'
          get 'deny'
        end
      end
    end

    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/poll.rb
class Poll
  class InvalidChoiceError < StandardError; end
  class ChoiceRequiredError < StandardError; end

  include Mongoid::Document
  include Mongoid::Timestamps
  include ActsAsList::Mongoid

  field :state, type: String, default: 'inactive'
  field :question, type: String
  field :start_date, type: DateTime
  field :end_date, type: DateTime

  attr_accessible :question, :start_date, :end_date, :choices_attributes

  belongs_to :project

  paginates_per 20

  embeds_many :choices, cascade_callbacks: true
  accepts_nested_attributes_for :choices, reject_if: proc { |attributes| attributes[:content].blank? }, allow_destroy: true

  validates :question, presence: true
  validates_associated :choices

  scope :active, where(state: "active")
  scope :inactive, where(state: "inactive")

  state_machine initial: :inactive do
    event :activate do
      transition all => :active
    end

    event :deactivate do
      transition all => :inactive
    end
  end

  def vote(choice_id)
    begin
      self.vote!(choice_id)
    rescue InvalidChoiceError, ChoiceRequiredError => e
      self.errors.add :choices, e.message
      false
    end
  end

  def vote!(choice_id)
    raise ChoiceRequiredError, "choice required" if choice_id.blank?
    begin
      choice = self.choices.find(choice_id)
    rescue Mongoid::Errors::DocumentNotFound
      raise InvalidChoiceError, "choice_id could not be found"
    end
    choice.votes += 1
    choice.save
  end
end

app/controllers/admin/polls_controller.rb
class Admin::PollsController < AdminController
  respond_to :html, :json

  def index
  end

  def new
    @poll = @project.polls.new
    2.times { @poll.choices.build }
  end

  def edit
    @poll = @project.polls.find(params[:id])
  end

  def show
    @poll = @project.polls.find(params[:id])
    respond_with @poll
  end

  def create
    @poll = @project.polls.new(params[:poll])
    @poll.save
    respond_with @poll, location: [:admin, @project, @poll]
  end

  def update
    @poll = @project.polls.find(params[:id])
    @poll.update_attributes(params[:poll])
    respond_with @poll, location: [:admin, @project, @poll]
  end

  def destroy
    @poll = @project.polls.find(params[:id])
    @poll.destroy

    respond_with @poll, location: admin_project_polls_url do |format|
      format.json { render json: '{ "status":"success" }', status: :ok }
    end
  end

  def activate
    @poll = @project.polls.find(params[:id])
    @poll.activate

    respond_with @poll do |format|
      format.html { redirect_to [:admin, @project, @poll] }
      format.json { render json: '{ "status":"success" }', status: :ok }
    end
  end

  def deactivate
    @poll = @project.polls.find(params[:id])
    @poll.deactivate

    respond_with @poll do |format|
      format.html { redirect_to [:admin, @project, @poll] }
      format.json { render json: '{ "status":"success" }', status: :ok }
    end
  end
end

app/controllers/api/polls_controller.rb
class Api::PollsController < ApplicationController
  before_filter :load_project, :check_for_project

  respond_to :json, :xml

  def index
    params[:sort_direction] ||= "asc"
    
    @polls = @project.polls
    @polls = @polls.where(state: params[:state]) if params[:state]
    @polls = @polls.order_by(params[:sort_column], params[:sort_direction]) if params[:sort_column]
    @polls = @polls.page(params[:page])
    @polls = @polls.per(params[:per_page]) if params[:per_page]

    respond_with :api, @project, @polls
  end

  def vote
    poll = @project.polls.active.find(params[:id])
    poll.vote(params['choice']['id'])

    respond_with :api, @project, @poll
  end

  def show
    @poll = @project.polls.find(params[:id])

    respond_with :api, @project, @poll
  end
end

app/views/admin/polls/_form.html.haml
%p
  = link_to 'Back', admin_project_polls_path(@project), title: "Back", class: "btn btn-inverse"

.row
  .span6
    = form_for [:admin, @project, @poll], html: {multipart: true, class: "form-horizontal"} do |f|
      - if @poll.errors.any?
        .alert.alert-error
          %p
            %b
              = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
          %ul
            - @poll.errors.full_messages.each do |msg|
              %li= msg

      %fieldset
        %legend= controller_action
        .control-group
          = f.label :question, class: "control-label"
          .controls= f.text_field :question

        #choices.control-group
          = f.label :choices, class: "control-label"
          .controls
            %p= link_to '<i class="icon-plus"></i>'.html_safe, "#", class: "btn add-poll-choice"
            = f.fields_for :choices do |c|
              %p.choice
                = c.hidden_field :id unless c.object.new_record?
                = c.text_field :content
                - if c.object.new_record?
                  = link_to '<i class="icon-minus"></i>'.html_safe, "#", class: "btn remove-poll-choice"
                - else
                  = link_to '<i class="icon-minus"></i>'.html_safe, polymorphic_url([:admin, @project, @poll, c.object], format: :json), method: :delete, confirm: 'Are you sure?', remote: true, class: "btn remove"
                = c.file_field :image

        .control-group
          = f.label :start_date, class: "control-label"
          .controls= f.text_field :start_date, class: "datetimepicker"

        .control-group
          = f.label :end_date, class: "control-label"
          .controls= f.text_field :end_date, class: "datetimepicker"

        .form-actions
          = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/polls/index.html.haml
%p
  = link_to '<i class="icon-plus"></i> New Poll'.html_safe, new_admin_project_poll_path(@project, @poll), class: "btn", title: "New"

.well
  %h6 Stats
  #{@project.polls.all.count} total

%textarea{class: "tmpl", "data-project" => "#{@project.name}", "data-model" => "#{controller_name}", "data-action" => "#{action_name}"}
  %tr{class: "${state}"}
    %td
      = link_to '${question}', admin_url + '${id}'
      %div{class: "actions ${state}"}
        = link_to '<i class="icon-ok-circle"></i>'.html_safe, admin_url + '${id}/activate.json', remote: true, class: "state activate btn", title: "Approve"
        = link_to '<i class="icon-ban-circle"></i>'.html_safe, admin_url + '${id}/deactivate.json', remote: true, class: "state deactivate btn", title: "Deny"
        = link_to '<i class="icon-edit"></i>'.html_safe, admin_url + '${id}/edit', class: "btn", title: "Edit"
        = link_to '<i class="icon-trash"></i>'.html_safe, admin_url + '${id}.json', remote: true, confirm: 'Are you sure?', method: :delete, class: "btn delete", title: "Delete"
    %td {{each choices}}-${choice.content} {{/each}}
    %td ${start_date}
    %td ${end_date}
    %td ${state}
    %td ${created_at}

%table.table.table-striped.table-bordered
  %tr
    %th Question
    %th Choices
    %th Start Date
    %th End Date
    %th State
    %th Created At

app/views/admin/polls/show.html.haml
- unless notice.blank?
  #notice.alert= notice

%p
  = link_to 'Back', admin_project_polls_path(@project), title: "Back", class: "btn btn-inverse"
  = link_to '<i class="icon-plus"></i>'.html_safe, new_admin_project_poll_path(@project, @signup), class: "btn", title: "Edit"
  = link_to '<i class="icon-edit"></i>'.html_safe, edit_admin_project_poll_path(@project), title: "Edit", class: "btn"

.row
  .span6
    = form_tag vote_api_project_poll_path(@project, @poll), class: "form-horizontal", method: :put do
      %fieldset
        %legend= @poll.question
        - @poll.choices.each do |choice|
          .control-group
            .control-label= radio_button :choice, :id, choice.id
            .controls
              = "#{choice.content} (#{choice.votes} votes)"
              - if choice.image?
                %br
                = image_tag("#{choice.image.url}")

        .control-group
          .control-label Start Date
          .controls
            .uneditable-input= @poll.start_date

        .control-group
          .control-label End Date
          .controls
            .uneditable-input= @poll.end_date

        .control-group
          .control-label Created At
          .controls
            .uneditable-input= @poll.created_at

        .control-group
          .control-label Updated At
          .controls
            .uneditable-input= @poll.updated_at

        .control-group
          .control-label State
          .controls
            .uneditable-input= @poll.state

        .form-actions
          = submit_tag "Vote", class: 'btn btn-primary'