config/routes.rb
require 'sidekiq/web'

Facepuncher::Application.routes.draw do

  root to: 'projects#show'

  resources :projects do
    member do
      match '/index' => 'projects#show'
    end
  end

  namespace :api do
    resources :project do
      resources :signups
      resources :events
      resources :videos
      resources :images
      resources :feeds
      resources :posts
      resources :facebook_albums
      resources :facebook_events

      resources :polls do
        put 'vote', on: :member
      end

      resources :submissions do
        post 'submit', on: :member
      end
    end
  end

  match '/admin' => 'admin/projects#index', as: 'user_root'

  # ADMIN ROUTES
  devise_for :users

  namespace :admin do
    root to: "projects#index"

    resources :users

    resources :projects do
      post 'queue_deploy', on: :collection

      member do
        get 'activate'
        get 'deactivate'
      end

      resources :signups
      resources :feeds
      resources :facebook_albums
      resources :facebook_events
      resources :view_templates

      resources :videos do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :releases do
        member do
          get 'go_live'
        end
      end

      resources :images do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :events do
        collection do
          post 'import'
        end
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :polls do
        resources :choices

        member do
          get 'activate'
          get 'deactivate'
        end
      end

      resources :submissions do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :posts do
        member do
          put 'up'
          put 'down'
          get 'approve'
          get 'deny'
        end
      end
    end

    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/project.rb
require 'mongoid/carrierwave_fix'

class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::CarrierwaveFix

  field :state, type: String, default: 'inactive'
  field :name, type: String
  field :description, type: String
  field :facebook_app_id, type: String
  field :facebook_app_secret, type: String
  field :google_analytics_tracking_code, type: String
  field :production_url, type: String
  field :repo, type: String

  index :name, unique: true

  attr_accessible :name, :description, :facebook_app_id, :facebook_app_secret, :google_analytics_tracking_code, :production_url, :repo

  after_create :generate_master_release

  has_many :events, dependent: :destroy
  has_many :signups, dependent: :destroy
  has_many :polls, dependent: :destroy
  has_many :videos, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :submissions, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :feeds, dependent: :destroy
  has_many :facebook_albums, dependent: :destroy
  has_many :facebook_events, dependent: :destroy
  has_many :releases, dependent: :destroy
  has_many :view_templates, dependent: :destroy

  scope :active, where(state: 'active')
  scope :inactive, where(state: 'inactive')

  paginates_per 50

  validates :name, presence: true, uniqueness: true
  validates :repo, presence: true

  state_machine initial: :inactive do
    event :activate do
      transition inactive: :active
    end

    event :deactivate do
      transition active: :inactive
    end
  end

  def touch
    self.updated_at = Time.current
    self.save
  end

  def to_param
    self.name
  end

  def live_release
    self.releases.where(state: "live").limit(1).first
  end

  def next_release
    past = self.releases.past
    past.empty? ? nil : past.first
  end

  def self.find_by_name(name)
    where(name: name).limit(1).first
  end

  protected
  def generate_master_release
    self.releases.create!
    DeployProject.perform_async self.name
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  respond_to :html, :json, except: :queue_deploy

  def index
    @projects = Project.order_by("name", "asc").page(params[:page])
    respond_with @projects
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find_by_name(params[:id])
  end

  def show
    @project = Project.find_by_name(params[:id])
    respond_with @project
  end

  def create
    @project = Project.new(params[:project])
    @project.save
    respond_with @project, location: [:admin, @project]
  end

  def update
    @project = Project.find_by_name(params[:id])
    @project.update_attributes(params[:project])
    respond_with @project, location: [:admin, @project]
  end

  def destroy
    @project = Project.find_by_name(params[:id])
    @project.destroy

    respond_with @project, location: admin_projects_url do |format|
      format.json { render json: '{ "status":"success" }', status: :ok }
    end
  end

  def activate
    @project = Project.find_by_name(params[:id])
    @project.activate

    respond_with @project do |format|
      format.html { redirect_to admin_projects_url }
      format.json { render json: '{ "status":"success" }', status: :ok }
    end
  end

  def deactivate
    @project = Project.find_by_name(params[:id])
    @project.deactivate

    respond_with @project do |format|
      format.html { redirect_to admin_projects_url }
      format.json { render json: '{ "status":"success" }', status: :ok }
    end
  end

  def queue_deploy
    DeployProject.queue_active

    respond_with @project, location: admin_projects_url do |format|
      format.json { render json: '{ "status":"success" }',  status: :ok }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < PageController
  respond_to :html, :json

  prepend_view_path APP_CONFIG['project_path'] if Rails.env.development?

  def show
    @image = @project.images.new
    @post = @project.posts.new
    @poll = @project.polls.new
    @event = @project.events.new
    @event.build_location
    @video = @project.videos.new
    @signup = @project.signups.new

    Project.reflect_on_all_associations(:references_many).map(&:class_name).each do |model_class|
      model = model_class.underscore.to_sym
      key = model.to_s.tableize
      if @project.send(key).respond_to?(:cached_results)
        results = Cacheable.get(@project.name, model)
        instance_variable_set("@#{key}", results)
      end
    end

    @signed_request = decode_signed_request(params[:signed_request], @project.facebook_app_id, @project.facebook_app_secret) if @project.facebook_app_id && @project.facebook_app_secret
    @liked = @signed_request['page']['liked'] rescue false
    @liked = true if Rails.env.development?

    if Rails.env.development? || stale?(etag: [@project, params[:signed_request]], last_modified: @project.updated_at.utc, public: true)
      render "#{@project.name}/index"
    end
  end

  def deauthorize
    render nothing: true
  end
end

app/views/admin/projects/_form.html.haml
%p
  = link_to 'Back', admin_projects_path, title: "Back", class: "btn btn-inverse"

.row
  .span6
    = form_for [:admin, @project], html: {multipart: true, class: "form-horizontal"} do |f|
      - if @project.errors.any?
        .alert.alert-error
          %p
            %b
              = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
          %ul
            - @project.errors.full_messages.each do |msg|
              %li= msg

      %fieldset
        %legend= controller_action
        .control-group
          = f.label :name, class: "control-label"
          .controls= f.text_field :name

        .control-group
          = f.label :description, class: "control-label"
          .controls= f.text_field :description

        .control-group
          = f.label :facebook_app_id, 'Facebook app ID', class: "control-label"
          .controls= f.text_field :facebook_app_id

        .control-group
          = f.label :facebook_app_secret, class: "control-label"
          .controls= f.text_field :facebook_app_secret

        .control-group
          = f.label :repo, class: "control-label"
          .controls= f.text_field :repo

        .control-group
          = f.label :google_analytics_tracking_code, class: "control-label"
          .controls= f.text_field :google_analytics_tracking_code

        .control-group
          = f.label :production_url, class: "control-label"
          .controls= f.text_field :production_url

        .form-actions
          = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/projects/index.html.haml
%p
  = link_to '<i class="icon-plus"></i> New Project'.html_safe, new_admin_project_path, class: "btn", title: "New"
  = link_to '<i class="icon-list-alt"></i> Queue Deploy'.html_safe, queue_deploy_admin_projects_path(format: :json), remote: true, method: :post, confirm: 'Are you sure?', class: "btn deploy", title: "Queue Deploy"

= paginate @projects

%table.table.table-striped.table-bordered
  %tr
    %th.auto Name
    %th{width: 110} Facebook App ID
    %th{width: 99} Live Branch
    %th{width: 111}

  - @projects.each do |project|
    %tr{class: project.active? ? nil : "inactive"}
      %td
        = link_to project.name, [:admin, project]
        .actions
          = link_to '<i class="icon-edit"></i>'.html_safe, edit_admin_project_path(project), class: "btn", title: "Edit"
          - if project.active?
            = link_to '<i class="icon-ban-circle"></i>'.html_safe, deactivate_admin_project_path(project, format: :json), remote: true, class: "deactivate btn", title: "Deactivate"
          - else
            = link_to '<i class="icon-ok-circle"></i>'.html_safe, activate_admin_project_path(project, format: :json), remote: true, class: "activate btn", title: "Activate"
          = link_to '<i class="icon-trash"></i>'.html_safe, polymorphic_url([:admin, project], format: :json), remote: true, confirm: 'Are you sure?', method: :delete, class: "btn delete", title: "Delete"
      %td= project.facebook_app_id
      %td
        - project.releases.each do |release|
          - if release.state == "live"
            = link_to '<i class="icon-eye-open"></i> '.html_safe + truncate(release.branch, length: 10), project_path(project), class: "btn release", title: "Go to App : branch@#{release.branch}"

      %td
        = link_to '<i class="icon-home"></i>'.html_safe, [:admin, project], class: "btn home", title: "Project Summary"
        = link_to '<i class="icon-asterisk"></i> Repo'.html_safe, project.repo, remote: true, class: "btn repo", title: project.repo

= paginate @projects

app/views/admin/projects/show.html.haml
- unless notice.blank?
  #notice.alert= notice

%p
  = link_to 'Back', admin_projects_path, title: "Back", class: "btn btn-inverse"
  = link_to '<i class="icon-eye-open"></i>'.html_safe, project_path(@project), title: "Go to App", class: "btn"
  = link_to '<i class="icon-edit"></i>'.html_safe, edit_admin_project_path(@project), title: "Edit", class: "btn"
  - if @project.inactive?
    = link_to '<i class="icon-ok-circle"></i>'.html_safe, activate_admin_project_path(@project, format: :json), remote: true, title: "Activate", class: "activate btn"
  - elsif
    = link_to '<i class="icon-ban-circle"></i>'.html_safe, deactivate_admin_project_path(@project, format: :json), remote: true, title: "Deactivate", class: "deactivate btn"

.row
  .span6
    %table.table.table-bordered
      %tr
        %td Created at
        %td= @project.created_at
      %tr
        %td Updated at
        %td= @project.updated_at
      %tr
        %td Name
        %td
          %b
            = @project.name
      %tr
        %td Description
        %td= @project.description

      %tr
        %td facebook_app_id
        %td= @project.facebook_app_id

      %tr
        %td facebook_app_secret
        %td= @project.facebook_app_secret

      %tr
        %td git repo
        %td= @project.repo

      %tr
        %td google_analytics_tracking_code
        %td= @project.google_analytics_tracking_code

      %tr
        %td production_url
        %td= link_to @project.production_url

      %tr
        %td state
        %td= @project.state