config/routes.rb
require 'sidekiq/web'

Facepuncher::Application.routes.draw do

  root to: 'projects#show'

  resources :projects do
    member do
      match '/index' => 'projects#show'
    end
  end

  namespace :api do
    resources :project do
      resources :signups
      resources :events
      resources :videos
      resources :images
      resources :feeds
      resources :posts
      resources :facebook_albums
      resources :facebook_events

      resources :polls do
        put 'vote', on: :member
      end

      resources :submissions do
        post 'submit', on: :member
      end
    end
  end

  match '/admin' => 'admin/projects#index', as: 'user_root'

  # ADMIN ROUTES
  devise_for :users

  namespace :admin do
    root to: "projects#index"

    resources :users

    resources :projects do
      post 'queue_deploy', on: :collection

      member do
        get 'activate'
        get 'deactivate'
      end

      resources :signups
      resources :feeds
      resources :facebook_albums
      resources :facebook_events
      resources :view_templates

      resources :videos do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :releases do
        member do
          get 'go_live'
        end
      end

      resources :images do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :events do
        collection do
          post 'import'
        end
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :polls do
        resources :choices

        member do
          get 'activate'
          get 'deactivate'
        end
      end

      resources :submissions do
        member do
          get 'approve'
          get 'deny'
        end
      end

      resources :posts do
        member do
          put 'up'
          put 'down'
          get 'approve'
          get 'deny'
        end
      end
    end

    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/image.rb
class Image
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActsAsList::Mongoid

  field :state, type: String, default: 'pending'
  field :name, type: String
  field :description, type: String

  attr_accessible :name, :description, :image

  belongs_to :project

  paginates_per 20

  mount_uploader :image, ImageGridUploader

  scope :pending, where(state: "pending")
  scope :approved, where(state: "approved")
  scope :denied, where(state: "denied")

  validates :image, presence: true

  state_machine initial: :pending do
    event :approve do
      transition [:pending, :denied] => :approved
    end

    event :deny do
      transition [:pending, :approved] => :denied
    end
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < AdminController
  respond_to :html, :json

  def index
  end

  def new
    @image = @project.images.new
  end

  def edit
    @image = @project.images.find(params[:id])
  end

  def show
  end

  def create
    @image = @project.images.new(params[:image])
    @image.save
    respond_with @image, location: [:admin, @project, @image]
  end

  def update
    @image = @project.images.find(params[:id])
    @image.update_attributes(params[:image])
    respond_with(@image, location: [:admin, @project, @image])
  end

  def destroy
    @image = @project.images.find(params[:id])
    @image.destroy
    
    respond_with @image, location: admin_project_images_url do |format|
      format.json { render json: '{ "status":"success" }', status: :ok }
    end
  end

  def approve
    @image = @project.images.find(params[:id])
    @image.approve

    respond_with @project do |format|
      format.html { redirect_to [:admin, @project, @image] }
      format.json { render json: '{ "status":"success" }', status: :ok }
    end
  end

  def deny
    @image = @project.images.find(params[:id])
    @image.deny

    respond_with @project do |format|
      format.html { redirect_to [:admin, @project, @image] }
      format.json { render json: '{ "status":"success" }', status: :ok }
    end
  end
end

app/controllers/api/images_controller.rb
class Api::ImagesController < ApplicationController
  before_filter :load_project, :check_for_project

  respond_to :json, :xml

  def index
    params[:sort_direction] ||= "asc"
    
    @images = @project.images
    @images = @images.where(state: params[:state]) if params[:state]
    @images = @images.order_by(params[:sort_column], params[:sort_direction]) if params[:sort_column]
    @images = @images.page(params[:page])
    @images = @images.per(params[:per_page]) if params[:per_page]

    respond_with :api, @project, @images
  end

  def show
    @image = @project.images.find(params[:id])

    respond_with :api, @project, @image
  end
end

app/views/admin/images/_form.html.haml
%p
  = link_to 'Back', admin_project_images_path(@project), title: "Back", class: "btn btn-inverse"

.row
  .span6
    = form_for [:admin, @project, @image], html: { multipart: true, class: "form-horizontal"} do |f|
      - if @image.errors.any?
        .alert.alert-error
          %p
            %b
              = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
          %ul
            - @image.errors.full_messages.each do |msg|
              %li= msg

      %fieldset
        %legend= controller_action
        .control-group
          = f.label :name, class: "control-label"
          .controls= f.text_field :name

        .control-group
          = f.label :description, class: "control-label"
          .controls= f.text_field :description

        .control-group
          = f.label :image, class: "control-label"
          .controls
            = f.file_field :image
            %br
            - unless @image.new_record?
              = image_tag @image.image.url

        .form-actions
          = f.hidden_field :project_id
          = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/images/index.html.haml
%p
  = link_to '<i class="icon-plus"></i> New Image'.html_safe, new_admin_project_image_path(@project), class: "btn", title: "New"

.well
  %h6 Stats
  #{@project.images.all.count} total

%textarea{class: "tmpl", "data-project" => "#{@project.name}", "data-model" => "#{controller_name}", "data-action" => "#{action_name}"}
  %tr{class: "${state}"}
    %td
      = link_to '${name}', admin_url + '${id}'
      %div{class: "actions ${state}"}
        = link_to '<i class="icon-ok-circle"></i>'.html_safe, admin_url + '${id}/approve.json', remote: true, class: "state approve btn", title: "Approve"
        = link_to '<i class="icon-ban-circle"></i>'.html_safe, admin_url + '${id}/deny.json', remote: true, class: "state deny btn", title: "Deny"
        = link_to '<i class="icon-edit"></i>'.html_safe, admin_url + '${id}/edit', class: "btn", title: "Edit"
        = link_to '<i class="icon-trash"></i>'.html_safe, admin_url + '${id}.json', remote: true, confirm: 'Are you sure?', method: :delete, class: "btn delete", title: "Delete"
    %td ${state}
    %td ${description}
    %td ${updated_at}
    %td {{if image.url}}<a href="${image.url}" class="btn" target="_blank"><i class="icon-picture"></i></a>{{/if}}

%table.table.table-striped.table-bordered
  %tr
    %th Name
    %th State
    %th Description
    %th Updated At
    %th Image?

app/views/admin/images/show.html.haml
- unless notice.blank?
  #notice.alert= notice

%p
  = link_to 'Back', admin_project_images_path(@project), title: "Back", class: "btn btn-inverse"
  = link_to '<i class="icon-plus"></i>'.html_safe, new_admin_project_image_path(@project), title: "New", class: "btn"

%textarea{class: "tmpl", "data-project" => "#{@project.name}", "data-model" => "#{controller_name}", "data-action" => "#{action_name}"}
  %tr{class: "${state}"}
    %td{colspan: 2}
      = link_to '<i class="icon-ok-circle"></i>'.html_safe, admin_url + '${id}/approve.json', remote: true, class: "state approve btn", title: "Approve"
      = link_to '<i class="icon-ban-circle"></i>'.html_safe, admin_url + '${id}/deny.json', remote: true, class: "state deny btn", title: "Deny"
      = link_to '<i class="icon-edit"></i>'.html_safe, admin_url + '${id}/edit', class: "btn", title: "Edit"
      = link_to '<i class="icon-trash"></i>'.html_safe, admin_url + '${id}', confirm: 'Are you sure?', method: :delete, class: "btn delete", title: "Delete"
  %tr
    %td Created at
    %td ${created_at}
  %tr
    %td Updated at
    %td ${updated_at}
  %tr
    %td State
    %td ${state}
  %tr
    %td Name
    %td ${name}
  %tr
    %td Description
    %td ${description}
  %tr
    %td Image
    %td {{if image.url}}<a href="${image.url}" class="btn" target="_blank"><i class="icon-picture"></i></a>{{/if}}

.row
  .span6
    %table.table.table-bordered